sudo: required
os: linux
services:
  - docker

before_install:
  - docker pull vowpalwabbit/travis-base
script:
  - docker run -a STDOUT -v `pwd`:/vw -t vowpalwabbit/travis-base /bin/bash -c "cd /vw && chmod +x ./build-linux.sh && ./build-linux.sh"

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
